version: '3.8'

services:
  whitelabel-rag:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY:?GEMINI_API_KEY environment variable is required}
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - CHROMA_DB_PATH=/app/chromadb_data
      - UPLOAD_FOLDER=/app/uploads
    volumes:
      - ./uploads:/app/uploads
      - ./chromadb_data:/app/chromadb_data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: ChromaDB as separate service
  # chromadb:
  #   image: chromadb/chroma:latest
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./chromadb_data:/chroma/chroma
  #   environment:
  #     - CHROMA_SERVER_HOST=0.0.0.0
  #     - CHROMA_SERVER_PORT=8000
  #   restart: unless-stopped

  # Optional: Redis for session storage
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   redis_data: